<?php
require_once 'dbconnect.php';
require_once 'firebase_config.php';

echo "<h1>📡 FIREBOARD JS DIAGNOSTIC</h1>";

$node = $_GET['node'] ?? 'SG-NODE2';
$creds = FirebaseConfig::getNodeConfig($node);

echo "<h3>1. Credentials being sent to JS:</h3>";
echo "<pre>";
print_r($creds);
echo "</pre>";

echo "<h3>2. Reference Path Check:</h3>";
echo "Dashboard is listening to: <b>$node/Sensor</b><br>";
echo "URL generated by PHP: <b>" . FirebaseConfig::getUrl('sensor', $node) . "</b><br>";

echo "<h3>3. Network Pre-flight:</h3>";
$url = FirebaseConfig::getUrl('sensor', $node);
$ch = curl_init($url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
$res = curl_exec($ch);
$http = curl_getinfo($ch, CURLINFO_HTTP_CODE);
echo "PHP-side connectivity check to Firebase: <b>HTTP $http</b><br>";

echo "<h3>🏁 Diag Complete</h3>";
?>
